all:	eje1 eje2 eje3 eje4 eje5 eje6 eje7 eje8 eje9

#compilacion de archivos
eje1:
	$(MAKE) -C main1
eje2:
	$(MAKE) -C main2
eje3:
	$(MAKE) -C main3
eje4:
	$(MAKE) -C main4
eje5:
	$(MAKE) -C main5
eje6:
	$(MAKE) -C main6
eje7:
	$(MAKE) -C main7
eje8:
	$(MAKE) -C main8
eje9:
	$(MAKE) -C main9

#ejecucion de archivos (uno por uno) el usuario decide cual quiere compilar

run1:
	./main1/a.out
run2:
	./main2/a.out
run3:
	./main3/a.out
run4:
	./main4/a.out
run5:
	./main5/a.out
run6:
	./main6/a.out
run7:
	./main7/a.out
run8:
	./main8/a.out
run9:
	./main9/a.out

